### ISSUE TITLE
add support for riseup email

### ISSUE THREAD

**Issue by oliviamriley** [DaylightingSociety/DeadManSwitch#10]
[riseup](https://riseup.net/en/about-us) is a cool tech collective that offers easy smtp access. ideally, we'll direct the user to their page and the user will register an account. then they'll select riseup from the dropdown of smtp providers, enter their credentials/config, and off they go. 

this is mainly just telling the user about riseup, but we'll need to add the same kind of stuff as #7

**Comment by oliviamriley** [comment]
so the js is there, but i think we'll need to reach out to riseup to work with them. registering an account requires an invite code from established members, so maybe we could work out some kind of partnership? idk.

**Comment by milo-trujillo** [comment]
Bah. Frustrating, but understandable on their end. There have to be other free email providers that don't require an arduous registration process (like tying the account to your phone number), that also support SMTP authentication.

**Comment by oliviamriley** [comment]
closing this as we've switched to mail.com
