### ISSUE TITLE
actually send emails

### ISSUE THREAD

**Issue by oliviamriley** [DaylightingSociety/DeadManSwitch#5]
rn we're using ethereal.email, and we should actually send emails.

that means we need an smtp server to connect to. we can use a gmail, but it'll get shut down as a bot.
we can ask each user to make an account, but gmail takes too long to sign up for.

this is really a question of finding an smtp provider that suits our needs, and until we have that, or a solution that circumvents that, we can't move forward with this.

**Comment by milo-trujillo** [comment]
If we're using generic SMTP, why not let the user supply a mail server and login credentials? Gmail takes a long time to sign up for, but presumably the user already has an email account *somewhere*.

Maybe we can have a drop-down menu for common email providers, so if they're using gmail, yahoo, etc, they don't need to look up the mail server address and port number?

**Comment by oliviamriley** [comment]
broken up into #7 #8 #9
